namespace HutongGames.PlayMaker
{
	public enum UIHint
	{
		None = 0,
		TextArea = 1,
		Behaviour = 2,
		Script = 3,
		Method = 4,
		Coroutine = 5,
		Animation = 6,
		Tag = 7,
		Layer = 8,
		Description = 9,
		Variable = 10,
		ScriptComponent = 11,
		Comment = 12,
		NamedColor = 13,
		NamedTexture = 14,
		FsmName = 15,
		FsmEvent = 16,
		FsmFloat = 17,
		FsmInt = 18,
		FsmBool = 19,
		FsmString = 20,
		FsmVector3 = 21,
		FsmGameObject = 22,
		FsmColor = 23,
		FsmRect = 24,
		FsmMaterial = 25,
		FsmTexture = 26,
		FsmQuaternion = 27,
		FsmObject = 28,
		FsmVector2 = 29,
		FsmEnum = 30,
		FsmArray = 31,
		AnimatorFloat = 32,
		AnimatorBool = 33,
		AnimatorInt = 34,
		AnimatorTrigger = 35,
		SortingLayer = 36
	}
}
